-- =========================================================
-- Stoney Verify Dashboard / Bot Schema
-- Full canonical schema.sql
-- =========================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =========================================================
-- audit_events
-- =========================================================
CREATE TABLE IF NOT EXISTS public.audit_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text NOT NULL,
  event_type text NOT NULL,
  related_id text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_events_pkey PRIMARY KEY (id)
);

-- =========================================================
-- audit_logs
-- =========================================================
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action text NOT NULL,
  token text,
  staff_id text,
  meta jsonb,
  created_at timestamp with time zone DEFAULT now()
);

-- =========================================================
-- bot_commands
-- =========================================================
CREATE TABLE IF NOT EXISTS public.bot_commands (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  guild_id text NOT NULL,
  action text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'pending'::text
    CHECK (
      status = ANY (
        ARRAY[
          'pending'::text,
          'processing'::text,
          'completed'::text,
          'failed'::text
        ]
      )
    ),
  result jsonb NOT NULL DEFAULT '{}'::jsonb,
  error text,
  requested_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  picked_up_at timestamp with time zone,
  completed_at timestamp with time zone,
  CONSTRAINT bot_commands_pkey PRIMARY KEY (id)
);

-- =========================================================
-- guild_members
-- =========================================================
CREATE TABLE IF NOT EXISTS public.guild_members (
  guild_id text NOT NULL,
  user_id text NOT NULL,
  username text,
  display_name text,
  avatar_url text,
  role_ids text[] NOT NULL DEFAULT '{}'::text[],
  role_names text[] NOT NULL DEFAULT '{}'::text[],
  highest_role_id text,
  highest_role_name text,
  in_guild boolean NOT NULL DEFAULT true,
  has_any_role boolean NOT NULL DEFAULT false,
  data_health text NOT NULL DEFAULT 'ok'::text
    CHECK (
      data_health = ANY (
        ARRAY[
          'ok'::text,
          'missing_role'::text,
          'stale'::text,
          'left_guild'::text,
          'unknown'::text
        ]
      )
    ),
  synced_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  has_unverified boolean NOT NULL DEFAULT false,
  has_verified_role boolean NOT NULL DEFAULT false,
  has_staff_role boolean NOT NULL DEFAULT false,
  has_secondary_verified_role boolean NOT NULL DEFAULT false,
  has_cosmetic_only boolean NOT NULL DEFAULT false,
  role_state text DEFAULT 'unknown'::text
    CHECK (
      role_state = ANY (
        ARRAY[
          'unverified_only'::text,
          'verified_ok'::text,
          'verified_conflict'::text,
          'staff_ok'::text,
          'staff_conflict'::text,
          'missing_unverified'::text,
          'missing_verified_role'::text,
          'booster_only'::text,
          'left_guild'::text,
          'unknown'::text,
          'bot_ok'::text
        ]
      )
    ),
  role_state_reason text,
  avatar_hash text,
  nickname text,
  roles jsonb DEFAULT '[]'::jsonb,
  top_role text,
  joined_at timestamp with time zone DEFAULT now(),
  previous_usernames jsonb NOT NULL DEFAULT '[]'::jsonb,
  previous_display_names jsonb NOT NULL DEFAULT '[]'::jsonb,
  previous_nicknames jsonb NOT NULL DEFAULT '[]'::jsonb,
  last_seen_username text,
  last_seen_display_name text,
  last_seen_nickname text,
  first_seen_at timestamp with time zone DEFAULT now(),
  last_seen_at timestamp with time zone DEFAULT now(),
  left_at timestamp with time zone,
  rejoined_at timestamp with time zone,
  times_joined integer NOT NULL DEFAULT 1,
  times_left integer NOT NULL DEFAULT 0,
  CONSTRAINT guild_members_pkey PRIMARY KEY (guild_id, user_id)
);

-- =========================================================
-- guild_role_rules
-- =========================================================
CREATE TABLE IF NOT EXISTS public.guild_role_rules (
  guild_id text NOT NULL,
  role_id text NOT NULL,
  role_name text NOT NULL,
  role_group text NOT NULL
    CHECK (
      role_group = ANY (
        ARRAY[
          'unverified'::text,
          'verified'::text,
          'secondary_verified'::text,
          'staff'::text,
          'admin'::text,
          'cosmetic'::text,
          'excluded'::text
        ]
      )
    ),
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT guild_role_rules_pkey PRIMARY KEY (guild_id, role_id)
);

-- =========================================================
-- guild_roles
-- =========================================================
CREATE TABLE IF NOT EXISTS public.guild_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  guild_id text NOT NULL,
  role_id text NOT NULL,
  name text NOT NULL,
  position integer NOT NULL DEFAULT 0,
  member_count integer DEFAULT 0,
  CONSTRAINT guild_roles_pkey PRIMARY KEY (id)
);

-- =========================================================
-- member_joins
-- =========================================================
CREATE TABLE IF NOT EXISTS public.member_joins (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  guild_id text NOT NULL,
  user_id text NOT NULL,
  username text,
  joined_at timestamp with time zone DEFAULT now(),
  CONSTRAINT member_joins_pkey PRIMARY KEY (id)
);

-- =========================================================
-- raid_events
-- =========================================================
CREATE TABLE IF NOT EXISTS public.raid_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  guild_id text DEFAULT ''::text,
  join_count integer NOT NULL DEFAULT 0,
  window_seconds integer NOT NULL DEFAULT 0,
  severity text NOT NULL,
  summary text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT raid_events_pkey PRIMARY KEY (id)
);

-- =========================================================
-- staff_metrics
-- =========================================================
CREATE TABLE IF NOT EXISTS public.staff_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  guild_id text NOT NULL,
  staff_id text NOT NULL,
  staff_name text,
  tickets_handled integer DEFAULT 0,
  approvals integer DEFAULT 0,
  denials integer DEFAULT 0,
  avg_response_minutes integer DEFAULT 0,
  last_active timestamp with time zone DEFAULT now(),
  CONSTRAINT staff_metrics_pkey PRIMARY KEY (id)
);

-- =========================================================
-- staff_users
-- =========================================================
CREATE TABLE IF NOT EXISTS public.staff_users (
  user_id uuid NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  role text NOT NULL DEFAULT 'staff'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT staff_users_pkey PRIMARY KEY (user_id),
  CONSTRAINT staff_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

-- =========================================================
-- ticket_categories
-- =========================================================
CREATE TABLE IF NOT EXISTS public.ticket_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  guild_id text NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  color text DEFAULT '#45d483'::text,
  created_at timestamp with time zone DEFAULT now(),
  staff_role_ids text[] DEFAULT '{}'::text[],
  staff_role_names text[] DEFAULT '{}'::text[],
  CONSTRAINT ticket_categories_pkey PRIMARY KEY (id)
);

-- =========================================================
-- tickets
-- =========================================================
CREATE TABLE IF NOT EXISTS public.tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  guild_id text NOT NULL,
  user_id text NOT NULL,
  username text,
  title text NOT NULL,
  category text NOT NULL,
  status text NOT NULL DEFAULT 'open'::text,
  priority text NOT NULL DEFAULT 'medium'::text,
  claimed_by text,
  closed_by text,
  closed_reason text,
  initial_message text,
  ai_category_confidence numeric DEFAULT 0,
  mod_suggestion text,
  mod_suggestion_confidence numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  closed_at timestamp with time zone,
  discord_thread_id text,
  assigned_to text,
  reopened_at timestamp with time zone,
  sla_deadline timestamp with time zone,
  channel_id text,
  channel_name text,
  is_ghost boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by text,
  transcript_url text,
  transcript_message_id text,
  transcript_channel_id text,
  source text DEFAULT 'discord'::text,
  CONSTRAINT tickets_pkey PRIMARY KEY (id)
);

-- =========================================================
-- ticket_messages
-- =========================================================
CREATE TABLE IF NOT EXISTS public.ticket_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ticket_id uuid NOT NULL,
  author_id text NOT NULL,
  author_name text,
  content text NOT NULL,
  message_type text NOT NULL DEFAULT 'staff'::text,
  created_at timestamp with time zone DEFAULT now(),
  attachments jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT ticket_messages_pkey PRIMARY KEY (id),
  CONSTRAINT ticket_messages_ticket_id_fkey
    FOREIGN KEY (ticket_id) REFERENCES public.tickets(id)
);

-- =========================================================
-- ticket_notes
-- =========================================================
CREATE TABLE IF NOT EXISTS public.ticket_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ticket_id uuid NOT NULL,
  staff_id text NOT NULL,
  staff_name text,
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ticket_notes_pkey PRIMARY KEY (id),
  CONSTRAINT ticket_notes_ticket_id_fkey
    FOREIGN KEY (ticket_id) REFERENCES public.tickets(id)
);

-- =========================================================
-- users
-- =========================================================
CREATE TABLE IF NOT EXISTS public.users (
  id text NOT NULL,
  data jsonb NOT NULL,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);

-- =========================================================
-- vc_verify_sessions
-- =========================================================
CREATE TABLE IF NOT EXISTS public.vc_verify_sessions (
  token text NOT NULL,
  guild_id bigint NOT NULL,
  ticket_channel_id bigint NOT NULL,
  requester_id bigint NOT NULL,
  owner_id bigint NOT NULL,
  vc_channel_id bigint,
  queue_channel_id bigint,
  queue_message_id bigint,
  status text NOT NULL DEFAULT 'PENDING'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  accepted_at timestamp with time zone,
  accepted_by bigint,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  canceled_at timestamp with time zone,
  canceled_by bigint,
  access_minutes integer NOT NULL DEFAULT 30,
  revoke_at timestamp with time zone,
  last_watchdog_at timestamp with time zone,
  meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT vc_verify_sessions_pkey PRIMARY KEY (token)
);

-- =========================================================
-- verification_flags
-- =========================================================
CREATE TABLE IF NOT EXISTS public.verification_flags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  guild_id text NOT NULL,
  user_id text NOT NULL,
  username text,
  score integer NOT NULL DEFAULT 0,
  reasons jsonb DEFAULT '[]'::jsonb,
  flagged boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT verification_flags_pkey PRIMARY KEY (id)
);

-- =========================================================
-- verification_kick_timers
-- =========================================================
CREATE TABLE IF NOT EXISTS public.verification_kick_timers (
  channel_id text NOT NULL,
  guild_id text NOT NULL,
  owner_id text NOT NULL,
  started_at timestamp with time zone NOT NULL,
  hours integer NOT NULL,
  started_by text,
  updated_at timestamp with time zone,
  CONSTRAINT verification_kick_timers_pkey PRIMARY KEY (channel_id)
);

-- =========================================================
-- verification_tokens
-- =========================================================
CREATE TABLE IF NOT EXISTS public.verification_tokens (
  token text NOT NULL CHECK (length(token) >= 6),
  webhook_url text NOT NULL CHECK (length(webhook_url) > 0),
  expires_at timestamp with time zone NOT NULL,
  used boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  guild_id text,
  channel_id text,
  requester_id text,
  decision text DEFAULT 'PENDING'::text,
  decided_by text,
  decided_at timestamp with time zone,
  user_id text,
  submitted boolean DEFAULT false,
  submitted_at timestamp with time zone,
  ai_status text,
  owner_display_name text,
  owner_username text,
  owner_tag text,
  approved_user_id text,
  updated_at timestamp with time zone,
  status text DEFAULT 'pending'::text
    CHECK (
      status = ANY (
        ARRAY[
          'pending'::text,
          'submitted'::text,
          'approved'::text,
          'denied'::text,
          'resubmit'::text,
          'used'::text,
          'expired'::text
        ]
      )
    ),
  requester_display_name text,
  requester_username text,
  requester_avatar_url text,
  requester_role_ids text[] DEFAULT '{}'::text[],
  requester_role_names text[] DEFAULT '{}'::text[],
  expected_role_state text DEFAULT 'unverified_only'::text
    CHECK (
      expected_role_state = ANY (
        ARRAY[
          'unverified_only'::text,
          'verified_ok'::text,
          'staff_ok'::text,
          'unknown'::text
        ]
      )
    ),
  actual_role_state text DEFAULT 'unknown'::text
    CHECK (
      actual_role_state = ANY (
        ARRAY[
          'unverified_only'::text,
          'verified_ok'::text,
          'verified_conflict'::text,
          'staff_ok'::text,
          'staff_conflict'::text,
          'missing_unverified'::text,
          'missing_verified_role'::text,
          'booster_only'::text,
          'left_guild'::text,
          'unknown'::text,
          'bot_ok'::text
        ]
      )
    ),
  role_sync_ok boolean DEFAULT false,
  role_sync_reason text,
  decided_by_display_name text,
  decided_by_username text,
  decided_by_avatar_url text,
  CONSTRAINT verification_tokens_pkey PRIMARY KEY (token)
);

-- =========================================================
-- warns
-- =========================================================
CREATE TABLE IF NOT EXISTS public.warns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  guild_id text NOT NULL,
  user_id text NOT NULL,
  username text,
  reason text NOT NULL,
  source_message text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT warns_pkey PRIMARY KEY (id)
);

-- =========================================================
-- world
-- =========================================================
CREATE TABLE IF NOT EXISTS public.world (
  id integer NOT NULL,
  data jsonb NOT NULL,
  CONSTRAINT world_pkey PRIMARY KEY (id)
);

-- =========================================================
-- PERFORMANCE INDEXES
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_audit_events_created_at
  ON public.audit_events(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at
  ON public.audit_logs(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_bot_commands_guild_id
  ON public.bot_commands(guild_id);

CREATE INDEX IF NOT EXISTS idx_bot_commands_status
  ON public.bot_commands(status);

CREATE INDEX IF NOT EXISTS idx_bot_commands_created_at
  ON public.bot_commands(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_guild_members_guild
  ON public.guild_members(guild_id);

CREATE INDEX IF NOT EXISTS idx_guild_members_active
  ON public.guild_members(guild_id, in_guild);

CREATE INDEX IF NOT EXISTS idx_guild_members_roles
  ON public.guild_members(guild_id, has_unverified, has_verified_role, has_staff_role);

CREATE INDEX IF NOT EXISTS idx_guild_members_updated_at
  ON public.guild_members(guild_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_guild_roles_guild
  ON public.guild_roles(guild_id);

CREATE INDEX IF NOT EXISTS idx_member_joins_guild
  ON public.member_joins(guild_id, joined_at DESC);

CREATE INDEX IF NOT EXISTS idx_raid_events_guild
  ON public.raid_events(guild_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_staff_metrics_guild
  ON public.staff_metrics(guild_id);

CREATE INDEX IF NOT EXISTS idx_ticket_categories_guild
  ON public.ticket_categories(guild_id);

CREATE INDEX IF NOT EXISTS idx_tickets_guild
  ON public.tickets(guild_id);

CREATE INDEX IF NOT EXISTS idx_tickets_status
  ON public.tickets(guild_id, status);

CREATE INDEX IF NOT EXISTS idx_tickets_updated_at
  ON public.tickets(guild_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_tickets_channel
  ON public.tickets(discord_thread_id);

CREATE INDEX IF NOT EXISTS idx_ticket_messages_ticket_id
  ON public.ticket_messages(ticket_id);

CREATE INDEX IF NOT EXISTS idx_ticket_notes_ticket_id
  ON public.ticket_notes(ticket_id);

CREATE INDEX IF NOT EXISTS idx_verification_flags_guild
  ON public.verification_flags(guild_id, flagged);

CREATE INDEX IF NOT EXISTS idx_verification_kick_timers_guild
  ON public.verification_kick_timers(guild_id);

CREATE INDEX IF NOT EXISTS idx_verification_tokens_guild
  ON public.verification_tokens(guild_id);

CREATE INDEX IF NOT EXISTS idx_verification_tokens_status
  ON public.verification_tokens(status);

CREATE INDEX IF NOT EXISTS idx_warns_guild
  ON public.warns(guild_id, created_at DESC);
